### ISSUE TITLE
duplicate, omit FCCM

### ISSUE THREAD

**Issue by warengonzaga** [web3phl/directory-api#14]
I received a report from the community member to remove FCCM, the one on the right side. Duplicate.
Ref: 
![image](https://user-images.githubusercontent.com/15052701/228442939-94ad36b3-fc9d-494a-8f52-816dc6b95cc2.png)

cc: @itsnalla

**Comment by chefallan** [comment]
checking right now.

**Comment by warengonzaga** [comment]
Closing added to dev branch.
